name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Build TinyYAML
        run: xcodebuild clean build -project TinyYAML.xcodeproj -scheme TinyYAML -configuration Release -derivedDataPath /tmp/tinybuild/tinyyaml CODE_SIGN_IDENTITY="-"
